services:
  ubft:
    platform: linux/amd64
    user: root
    build:
      context: ./
      dockerfile: ./scripts/Dockerfile

  ubft-root-genesis:
    extends:
      service: ubft
    volumes:
      - genesis:/genesis
      - root:/genesis/root
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Creating root genesis..." && \
        ubft root-node init \
          --home /genesis/root \
          --generate && \
        echo "Creating root trust base..." && \
        ubft trust-base generate \
          --home /genesis \
          --network-id 3 \
          --node-info /genesis/root/node-info.json &&  \
        echo "Signing root trust base..." && \
        ubft trust-base sign \
          --home /genesis/root \
          --trust-base /genesis/trust-base.json

  ubft-root:
    extends:
      service: ubft
    volumes:
      - genesis:/genesis
      - root:/genesis/root
    depends_on:
      ubft-root-genesis:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "nc", "-zv", "ubft-root", "8000" ]
      interval: 5s
    networks:
      - default
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Starting root node..." && \
        ubft root-node run \
          --home /genesis/root \
          --address "/ip4/$(hostname -i)/tcp/8000" \
          --trust-base /genesis/trust-base.json \
          --rpc-server-address "$(hostname -i):8002"

networks:
  default:

volumes:
  genesis:
  root:
