package zkverifier

import (
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

// SP1Verifier verifies SP1 zkVM proofs
type SP1Verifier struct {
	vkey        []byte
	enabled     bool
	ffiVerifier *SP1VerifierFFI
}

// NewSP1Verifier creates a new SP1 verifier
// vkeyPath: path to the SP1 verification key file (.vkey)
func NewSP1Verifier(vkeyPath string) (*SP1Verifier, error) {
	if vkeyPath == "" {
		return nil, fmt.Errorf("verification key path is required for SP1 verifier")
	}

	// Try to create FFI verifier first
	if ffiVerifier, err := NewSP1VerifierFFI(vkeyPath); err == nil {
		slog.Info("Using SP1 FFI verifier", "path", vkeyPath, "version", GetFFIVersion())
		return &SP1Verifier{
			vkey:        ffiVerifier.vkey,
			enabled:     true,
			ffiVerifier: ffiVerifier,
		}, nil
	} else {
		return nil, fmt.Errorf("SP1 FFI verifier not available: %w, vkeyPath: %s", err, vkeyPath)
	}

}

// readFile reads a file and returns its contents
func readFile(path string) ([]byte, error) {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve path: %w", err)
	}

	data, err := os.ReadFile(absPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read file %s: %w", absPath, err)
	}

	return data, nil
}

// VerifyProof verifies an SP1 compressed proof
//
// The proof should be a compressed SP1 proof generated by the prover.
// The proof includes:
// - Public inputs: previousStateRoot, newStateRoot, blockHash
// - Proof data: SP1 compressed proof bytes
//
// This function verifies that executing the program produces the expected
// state roots and block hash as public outputs.
func (v *SP1Verifier) VerifyProof(proof []byte, previousStateRoot []byte, newStateRoot []byte, blockHash []byte) error {
	if !v.enabled {
		return ErrVerifierNotConfigured
	}

	if len(proof) == 0 {
		return fmt.Errorf("%w: proof is empty", ErrInvalidProofFormat)
	}

	if len(previousStateRoot) != 32 {
		return fmt.Errorf("%w: previousStateRoot must be 32 bytes, got %d", ErrInvalidProofFormat, len(previousStateRoot))
	}

	if len(newStateRoot) != 32 {
		return fmt.Errorf("%w: newStateRoot must be 32 bytes, got %d", ErrInvalidProofFormat, len(newStateRoot))
	}

	if len(blockHash) != 32 {
		return fmt.Errorf("%w: blockHash must be 32 bytes, got %d", ErrInvalidProofFormat, len(blockHash))
	}

	slog.Debug("Verifying SP1 proof",
		"proof_size", len(proof),
		"prev_root", hex.EncodeToString(previousStateRoot[:8]),
		"new_root", hex.EncodeToString(newStateRoot[:8]),
		"block_hash", hex.EncodeToString(blockHash[:8]))

	return v.ffiVerifier.VerifyProof(proof, previousStateRoot, newStateRoot, blockHash)
}

func (v *SP1Verifier) ProofType() ProofType {
	return ProofTypeSP1
}

func (v *SP1Verifier) IsEnabled() bool {
	return v.enabled
}
